Add osiris and iris
interactivereduction/run-detection pull request #203
Opened 2023-12-11 08:32 UTC by keiranjprice101

Closes # 

## Description

2024-02-20 15:14 UTC, Pasarus requested changes
Great work here! really close to implementing for OSIRIS. Perhaps remove IRIS from the PR name?

Just a couple of questions to answer / improvements to implement and we are ready to merge I think.

2024-02-21 11:53 UTC, keiranjprice101 commented on rundetection/rules/osiris_rules.py
> +    def verify(self, job_request: JobRequest) -> None:
Because they are overrides, they inherit docstrings

2024-02-21 11:55 UTC, keiranjprice101 commented on rundetection/rules/osiris_rules.py
> +        (22500.0, 42500.0, 19000.03, 39000.0): 4,
Will double check this, thanks.

2024-02-23 08:43 UTC, keiranjprice101 commented on rundetection/rules/osiris_rules.py
> +        (22500.0, 42500.0, 19000.03, 39000.0): 4,
Addressed

2024-02-23 08:51 UTC, keiranjprice101 commented on .pylintrc
> +        duplicate-code
I removed this from project wide, and disabled it specifically on the duplicates within the rules. 

The reason I left it duplicate is I will open an issue to extract some of the stitch logic to the ABC rule or common rules in the future.

2024-02-26 08:55 UTC, Pasarus commented on .pylintrc
> +        duplicate-code
Ah makes sense in this scenario

2024-02-26 08:57 UTC, Pasarus approved these changes
Approved LGTM

2024-02-26 08:57 UTC, merged